### ISSUE TITLE
MXML tag without prefix causes NullPointerException

### ISSUE THREAD

**Issue by Harbs** [apache/royale-compiler#102]
The exception is generated in MXMLClassReferenceNodeBase on line 528:
`if (uri.equals("http://www.w3.org/1999/xhtml"))`

Some example MXML:
````
<palette:IconToggle id="leftButton"> 
    <materialIcon>
        <mdl:MaterialIcon text="format_align_left"/>
    </materialIcon>
</palette:IconToggle>
````
`palette:IconToggle` subclasses `mdl:IconToggle`

In this case `String uri = childTag.getURI();` results in `uri` being `null` for `<materialIcon>`

We should probably have an error which directs the user to fix this.

**Comment by Harbs** [comment]
FWIW, until recently I used an `mdl` prefix and it worked fine. A recent compiler change made the compiler much more picky about prefixes. (Same for `<js:style>`)

I wonder if prefixes should be optional for properties.

**Comment by Harbs** [comment]
@joshtynjala @aharui Thoughts?

**Comment by carlosrovira** [comment]
Hi Harbs,

`materialIcon` don't need to be prefixed but `palette`?

I'm saying this:

```mxml
<palette:IconToggle id="leftButton"> 
    <palette:materialIcon>
        <mdl:MaterialIcon text="format_align_left"/>
    </palette:materialIcon>
</palette:IconToggle>
```

**Comment by aharui** [comment]
The Royale compiler should be as picky as the Flex compiler.  I thought the Flex compiler was as picky as Josh was trying to make it, but Pashmina reported something that makes me think the Flex compiler might have been more lenient.  Hopefully Josh can investigate further.

**Comment by Harbs** [comment]
@carlosrovira It does, but instead of an error which says it's missing the prefix, we get a NullPointerException.

The compiler needs to report an error which helps the user find the problem.

I discovered this when I removed the `mdl` prefix because we're now getting a compiler error on that.

**Comment by Harbs** [comment]
> The Royale compiler should be as picky as the Flex compiler.
My main point was the NullPointerException which needs to be fixed.

Why should we be bound to the pickiness of Flex? It seems to me that a property of a class should be infer-able without the prefix.

**Comment by aharui** [comment]
Yes, for sure the NPE is a bug.  Josh probably didn't have a test for "no namespace".

I thought the reason to be picky was for XML validation.  I don't remember why Flex enforced whatever it enforced.

-Alex

**Comment by carlosrovira** [comment]
IDEs should benefit from this kind of fixes when writing a proper prefix then code intelligence could show a list of possible attributes. I think Flex had the same problem Josh fixed, IICRC, what seems to me a good fix. Other thing is if it needs to provide better error description like Harbs points.

**Comment by carlosrovira** [comment]
I just tested a similar case that gives error too due to latest changes:

```mxml
<j:List>
	<j:dataProvider>
		<fx:Array>
			<fx:String>Features</fx:String>
			<fx:String>Support</fx:String>
		</fx:Array>
	</j:dataProvider>
</j:List>
```

error trace:

> [INFO] Executing MXMLC in tool group Royale with args: [-load-config=/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/TourDeJewel/target/compile-app-config.xml, -source-map=true, -js-dynamic-access-unknown-members=true, -js-output=/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/TourDeJewel/target/javascript, -compiler.targets=JSRoyale, /Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/TourDeJewel/src/main/royale/App.mxml]
> /Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/TourDeJewel/src/main/royale/ListPlayGround.mxml(47): col: 7 Error: This tag is unexpected. It will be ignored.
> 
>                                                 <fx:Array>
>                                                 ^
> 
> /Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/TourDeJewel/src/main/royale/ListPlayGround.mxml(62): col: 7 Error: This tag is unexpected. It will be ignored.
> 
>                                                 <fx:Array>
>                                                 ^

(aside from the problem, did you notice that errors are printed twice?)

**Comment by joshtynjala** [comment]
I'll fix the null pointer exception next week when I get back from the US Thanksgiving holiday. I'll also test the Flex compiler more to see if I can find any exceptions that I missed (such as if Flex allowed no prefix on properties).

**Comment by aharui** [comment]
Seems like someone should revert the commit until Josh can redo it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aharui** [comment]
I reverted the commit for now.

**Comment by carlosrovira** [comment]
@joshtynjala please as part of the revision take a look at the example I posted where I use `fx:Array`. I guess is that `fx` prefix needs special handling to be allowed.

**Comment by joshtynjala** [comment]
The null reference exception appears to have been a pre-existing bug that Harbs just happened to coincidentally encounter as he was changing his code. I was able to fix it, though. I'll look into the issue that Carlos mentioned next.

**Comment by joshtynjala** [comment]
@carlosrovira I tried creating a simple Jewel app with the following code, but I could not reproduce your issue:

```mxml
<j:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
	xmlns:j="library://ns.apache.org/royale/jewel">
	<j:initialView>
		<j:View>
			<j:List>
				<j:dataProvider>
					<fx:Array>
						<fx:String>Features</fx:String>
						<fx:String>Support</fx:String>
					</fx:Array>
				</j:dataProvider>
			</j:List>
		</j:View>
	</j:initialView>
</j:Application>
```

**Comment by carlosrovira** [comment]
Hi Josh,
if you use TDJ and add to `ListPlayGround.mxml` in some `j:Card` component this

```mxml
                         <j:List>
				<j:dataProvider>
					<fx:Array>
						<fx:String>Features</fx:String>
						<fx:String>Support</fx:String>
					</fx:Array>
				</j:dataProvider>
			</j:List>
```

you should get the compilation fail. Just tried now and it failed.

Thanks

**Comment by joshtynjala** [comment]
@carlosrovira I still cannot reproduce the issue. I tried adding that code inside several different j:Card instances in ListPlayGround.mxml, but I did not see any errors. I tried the latest nightly build, and I also tried building the compiler locally from the develop branch.

**Comment by aharui** [comment]
FWIW, there are 3 possible allowed source configs for Carlos's scenario, depending on whether there is a defaultProperty for the component.  The j:dataProvider can be omitted and I think the fx:Array can as well.

So maybe there is something related to that that is making it so you can't reproduce it.

**Comment by carlosrovira** [comment]
Hi, I think I found something. I'm using maven to build TDJ and in that way I get errors. If I compile using `asconfig.json`in VSCode instead I get the build succeed. @joshtynjala Maybe you're trying with the second way? can you try to build with Maven?

Although, I think we should not have any issue related to the way we choose to build a project, for this continue to be a very strange issue.

Thanks

**Comment by joshtynjala** [comment]
I can reproduce the issue with Maven. However, I've determined that my recent changes did not cause it. I can reproduce a compiler error with 0.9.6 too.

It's a slightly different error, but I'm pretty certain that it's the same bug.

```
Error: In initializer for 'fx:Array' multiple initializer values are not permitted for target type '*'.

                                                <fx:String>Features</fx:String>
                                                ^
```

**Comment by joshtynjala** [comment]
@carlosrovira I have created a separate issue: #103

**Comment by carlosrovira** [comment]
Thanks Josh!
