### ISSUE TITLE
royale-maven-plugin does not support MXML tags for core types like Array, String, etc.

### ISSUE THREAD

**Issue by joshtynjala** [apache/royale-compiler#103]
Original bug report by @carlosrovira in this comment:

https://github.com/apache/royale-compiler/issues/102#issuecomment-559560120

I have determined that royale-maven-plugin does not provide the "components" from [_mxml-2009-manifest.xml_](https://github.com/apache/royale-asjs/blob/develop/frameworks/mxml-2009-manifest.xml) when it generates a config XML file to compile a project.

In a distribution's [_royale-config.xml_](https://github.com/apache/royale-asjs/blob/develop/frameworks/royale-config-template.xml) file, this manifest file is referenced using the `namespace` compiler option:

```
<namespaces>
  <namespace>
    <uri>http://ns.adobe.com/mxml/2009</uri>
    <manifest>mxml-2009-manifest.xml</manifest>
  </namespace>
</namespaces>
```

The royale-maven-plugin generates a config file with an empty namespaces tag, so these classes cannot be resolved from tags like `<fx:Array>` or `<fx:String>`, and it results in a compiler error:

> Error: This tag is unexpected. It will be ignored.

There's no way to provide the mappings directly in the config XML file, so the royale-maven-plugin will need to create a similar _mxml-2009-manifest.xml_ somewhere on the file system and reference that path in the config XML file. Presumably, the manifest would be created in the local _target_ folder.

**Comment by carlosrovira** [comment]
Hi Josh,
as I already reported in other email thread. The fix seems to have a collateral damage in a Core class `org.apache.royale.utils.object.defineSimpleProperty` since fails to compile for `Object.defineProperty`, can you take a look?. Thanks in advance

**Comment by carlosrovira** [comment]
I can confirm the fix is working.
thanks :)
