### ISSUE TITLE
switch case NaN issue

### ISSUE THREAD

**Issue by carlosrovira** [apache/royale-compiler#104]
Hi,

if we have a Number (e.j: `private var someNumber:Number = NaN;` and use a switch case structure with a option to match `NaN':

```
switch(someNumber)
{
...
     case NaN:
             doSomething();
```

when `someNumber` is `NaN` it does not enter switch case for `NaN`.

**Comment by greg-dove** [comment]
Did that work in legacy code? 
I'm kind of surprised if it did, it must be special cased in AVM if so because NaN !== NaN

**Comment by greg-dove** [comment]
If you can confirm it was working in legacy code, I can consider options, otherwise it should be possible to add a workaround inside the 'default:' clause
default:
if (isNaN(someNumber)) {
doSomething();

} else { any other stuff that may have been in default clause}
break;

**Comment by carlosrovira** [comment]
Hi Greg,
I must admit that I didn't try in a legacy environment, just was something I want to do and seems to me logic. But maybe it's not. So if is something we don't add please forget.

Other case is if legacy forgot to support something like this. Maybe if is something worth it and rest of people here thinks is helpful we can consider to add it, since will not break older code (since nobody will have it there as it was not supported before).

Thanks!

**Comment by Harbs** [comment]
It's not something I would guess would work. `NaN == NaN` resolves to false, and there's no reason a switch would be any different.

**Comment by greg-dove** [comment]
NaN is really 'special' for this stuff. It could perhaps be done for NaN as a literal, but you could also have a 'case myVar:' where myVar is another Number var that had a NaN value and there is no reasonable way the compiler could be sure of that for the general case at compile time to add special case code. I think it is actually correct as it is. I did not check legacy Flex compiler, but I suspect this is bytecode level anyhow. To me it falls in the same category as:
`[NaN].indexOf(NaN)`
which is also -1

**Comment by carlosrovira** [comment]
ok Thanks for your explanation about this :).
Closing this.

**Comment by Harbs** [comment]
For a full explanation on `NaN`, read here: https://stackoverflow.com/questions/10034149/why-is-nan-not-equal-to-nan

**Comment by aharui** [comment]
In Flex, compiled with MXMLC, in the standalone debugger:
```
var n:Number;
            trace(isNaN(n));
            switch (n) {
                case NaN:
                    trace("switch NAN!")
                    break;
                default:
                    trace("switch not NaN");
            }
```

outputs:
```
true
switch not NaN
```

So, NaN != NaN in switch statements in Flash.
