### ISSUE TITLE
[Bindable("change")] seems to be causing [Bindable] wrapping in Spark TextInput.text and some other places

### ISSUE THREAD

**Issue by aharui** [apache/royale-compiler#114]
When an getter/setter has [Bindable] metadata the compiler wraps the setter in a method prefixed with "bindable__".  This should not happen if [Bindable("someEvent")] metadata is used.  And doesn't happen in most cases.  But on Spark TextInput, the text getter/setter is being wrapped and shouldn't.  Also true in a few other classes.  Grep for "bindable__" on bin/js-debug/mx and bin/js-debug/spark.  The Emulation components shouldn't have any "bindable__" prefixes.  The APIs should always be using [Bindable("someEvent")].

**Comment by greg-dove** [comment]
Just a quick update. I picked this up also as a general issue when working on Binding unit tests, it was an issue for swf as well. I do have a fix for this, along with some other binding issues, supported by unit tests that I have been checking in Flex as well as Royale (swf and js). I need to migrate the unit tests to RoyaleUnit and will push this fix when the unit tests are ready. It might be a few days still.
