### ISSUE TITLE
Bad implicit casting to Function

### ISSUE THREAD

**Issue by yishayw** [apache/royale-compiler#126]
This
-                                       text = fdgc.labelFunction(fdgc.dataColumn).toString();
causes fdgc.dataColumn to be implicitly cast to Function, which of course fails.

This alternative syntax
+                    var labelFunction:Function = fdgc.labelFunction;
+                                       text = labelFunction(fdgc.dataColumn).toString();

fixes it.

**Comment by aharui** [comment]
What is the type of fdgc.labelFunction?
What was the generated code?
If labelFunction is Object then it might fool the compiler.

**Comment by yishayw** [comment]
fdgc.labelFunction is a Function

Compiled code is:

text = fdgc.labelFunction(/* implicit cast */ org.apache.royale.utils.Language.as(fdgc.dataColumn, Function, true)).toString();

**Comment by greg-dove** [comment]
Hi Yishay, I added that implicit casting for complex types , so feel obliged to fix it.

But so far I could not repro. 
Is there anything more specific you can share about the original scenario that would help me test it in a local repro?

I tried this:

``` private var _func:Function;
        public function get labelFunction():Function{
            if (_func == null) {
                _func = function(whatever:Object):String {return 'whatever'}
            }
            return _func;
        }
        
        [Test]
        public function test():void
        {
            var text:String = labelFunction({ }).toString();
            RoyaleUnitTestRunner.consoleOut(text);
            var selfRef:LanguageTesterTestImplicitCast = this;
            //try via member access
            text = selfRef.labelFunction({}).toString();
            RoyaleUnitTestRunner.consoleOut(text);
            assertTrue(true, 'not yet a test');

        }
```
But the output from the above looks like: 

```/**
 * @export
 */
flexUnitTests.language.LanguageTesterTestImplicitCast.prototype.test = function() {
  var /** @type {string} */ text = this.labelFunction({}).toString();
  testshim.RoyaleUnitTestRunner.consoleOut(text);
  var /** @type {flexUnitTests.language.LanguageTesterTestImplicitCast} */ selfRef = this;
  text = selfRef.labelFunction({}).toString();
  testshim.RoyaleUnitTestRunner.consoleOut(text);
  org.apache.royale.test.asserts.assertTrue(true, 'not yet a test');
};
```

**Comment by greg-dove** [comment]
hmm maybe I need to add a setter.... going to try that

**Comment by yishayw** [comment]
I haven't been able to come up with an isolated test case either. I don't know enough about the conditions for implicit casting to be efficient at this. FWIW, here's some more context from the original code

`        private function createListData(fdgc:IFooterDataGridColumn, i:Number):void
        {
            if (fdgc.renderer is IDropInListItemRenderer)
            {
//                var text:String = (fdgc.labelFunction != null) ? fdgc.labelFunction(fdgc.dataColumn) : fdgc.label;
				var text:String = "";
				if (fdgc.labelFunction != null)
				{
                     text = fdgc.labelFunction(fdgc.dataColumn).toString();
                    // var labelFunction:Function = fdgc.labelFunction;
				}`

IFooterDataGridColumn.as has these lines:

`        function set labelFunction(value:Function):void
        function get labelFunction():Function
        function set dataColumn(value:Object):void
        function get dataColumn():Object
`

and dataColumn is populated like this:

`					               <ns4:SummaryColumn operation='count' dataColumn='{LastName}'/>`

where LastName is

`							<mx:AdvancedDataGridColumn headerText="Last Name" dataField="LastName" width="140" textAlign="left" id="LastName"/>`

**Comment by aharui** [comment]
Here's a test case (I tested it by adding it to TestRoyaleExpressions.java).  I don't have time to fix it right now, I just had some time to try to reproduce it and got lucky.  The key seems to be that the setter for `b` has to be before the getter!

```    
    @Test
    public void testFunctionProperty()
    {
        IFunctionNode node = (IFunctionNode) getNode(
                "public class B { public function a():void { b(c); } public function set b(v:Function):void {}  public function get b():Function { return null; } public function get c():Object { return null; } public function set c(v:Object):void {} }",
                IFunctionNode.class, WRAP_LEVEL_PACKAGE);
        asBlockWalker.visitFunction(node);
        assertOut("/**\n * @export\n */\nB.prototype.a = function() {\n  this.b(this.c);\n}");
    }
```

**Comment by aharui** [comment]
Pushed the test case with @Ignore in 42338fb2aa375af58d034f9d5de3c05a4ff8d651

**Comment by greg-dove** [comment]
Thanks, much appreciated. I will look into this tomorrow my time. I have a few compiler bugs I have tracked down and need to somehow get minimal repros for other things too.

**Comment by greg-dove** [comment]
Thanks for the repro test case Alex. I'm not sure that a function call node from an accessor like this needs to follow all the subsequent code paths in the compiler, but we know it is working when the nameNode for the function call is resolving to the getter definition (which makes sense that it should also) and not the setter definition . So that's all I changed. Yishay, I'll leave it to you to confirm the fix in your original code and close the issue if it fixes the original problem. Thanks, Greg

**Comment by yishayw** [comment]
Confirmed.
