### ISSUE TITLE
Bad transpiling for Object's property in release mode

### ISSUE THREAD

**Issue by carlosrovira** [apache/royale-compiler#153]
I found a bug in Object transpiling.

This code:

```
var timing:Object = {
				duration: 1000, 
				iterations: Infinity
			}
```

is translating to:

`{duration:1E3,HF:Infinity}`

a workaround is to do:

```
var timing:Object =  new Object();
			timing["duration"] = 1000;
			timing["iterations"] = Infinity;
```

that transpiles to:

`{duration:1E3,iterations:Infinity}`

That works correctly

**Comment by Harbs** [comment]
I assume this is in minified code. That's to be expected.

You can use:
````
var timing:Object = {
    "duration": 1000, 
    "iterations": Infinity
}
````

If you don't want to use the quotes, you can compile with `-js-dynamic-access-unknown-members=true` That will reserve the property names.

**Comment by Harbs** [comment]
@carlosrovira  Closing this because it's not a bug.

**Comment by carlosrovira** [comment]
Hi Harbs,

sorry, I forgot to say that the project where I'm trying it has already `-js-dynamic-access-unknown-members=true;`

**Comment by Harbs** [comment]
Oh. Then it is a bug. ;)

**Comment by Harbs** [comment]
Do you have a simple test case?

**Comment by carlosrovira** [comment]
Yes, 

New Jewel SimpleLoader is the test case (037d49185874a8edc86d092dd3de8bd655c86a32)
You can change the `timings` object to the other way of declaring it showed here and try in an application with a code like this:

```
<j:SimpleLoader indeterminate="true"/>
```

You'll see the rotation is only done once instead to loop forever.

If you left the timings object in the current state it does work

**Comment by Harbs** [comment]
Gotcha.

I don't think it's a bug.

The JS is compiled when the library is packaged into a SWC. For this to work as you expect, the __library__ needs to be compiled using the `-js-dynamic-access-unknown-members=true`. If Jewel would be compiled with that option, it would work as you'd expect.

I use this extensively in my own libs and it works very well.

I'm not sure it makes sense to add that to framework libs. Quoting variable names is the way to go IMO for framework code.

**Comment by Harbs** [comment]
I just changed `SimpleLoader` to simpler code that should work fine.

**Comment by carlosrovira** [comment]
Ok Harbs, good to know. Thanks for letting me know. Closing this.
