### ISSUE TITLE
Support of private constructors limited

### ISSUE THREAD

**Issue by chrisdutz** [apache/royale-compiler#158]
It seems that with private constructors it's currently not allowed to:

1. types with private constructors can not be an argument in methods (both instance and static methods).
2. Return types with private constructors only works on static methods. non-static methods with these return types error.

This makes their usage quite limited. For example when trying to implement Enums in ActionScript.

**Comment by chrisdutz** [comment]
Here's a link to an example project demonstrating the issue:
https://drive.google.com/file/d/1SNMiH5xuUERbIiscuEH_JgcOLrBboj4j/view?usp=sharing

**Comment by Harbs** [comment]
@joshtynjala Can you look at this?

**Comment by chrisdutz** [comment]
[Enums.zip](https://github.com/apache/royale-compiler/files/5082937/Enums.zip)

**Comment by joshtynjala** [comment]
Looking into it...
