### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/royale-compiler#161]
https://github.com/apache/royale-compiler/blob/6f75df78d08d3c4a7f81a8d25d96b978972ee480/flex-compiler-oem/src/main/java/flex2/compiler/common/CompilerConfiguration.java#L702

This field is never used.

**Comment by carlosrovira** [comment]
Hi, thanks for let us know.
You also can submit PRs (Pull Request) and also join our dev mailing list here [1] to start conversation with the rest of us and eventually become committer for this project.

[1] https://royale.apache.org/mailing-lists/
