### ISSUE TITLE
Problems with initialization code for `static const` and `static var`

### ISSUE THREAD

**Issue by mrchnk** [apache/royale-compiler#169]
Problems with lazy initialization code for static members referencing other classes.

Simple ActionScript3 code

```
public class Enum {
  
  private static const _registry:EnumRegistry = new EnumRegistry();
  public function Enum(name:String) {
    _name = name;
    _registry.add((this as Object).constructor, this);
  }
  // ...
}
```

Will generate lazy-initialization const using properties (JSDoc was omitted):
```
Enum.get___registry = function() {
  var value = new EnumRegistry();
  Object.defineProperty(Enum, '_registry', { 
    value: value, 
    writable: false 
  });
  return value;
};

Object.defineProperties(Enum, {
  _registry: {
    get: Enum.get___registry,
    configurable: true
  }
});
```

Looks OK. Even with property redefinition, that code runs correctly.

But after the minimization process by Closure Compiler problem pops up.
```
// Enum becomes `v`, EnumRegistry becomes `x`, _registry becomes `m`
Object.defineProperties(v, {
  m: {
    get: function () {
      var a = new x;
      // '_registry' is not renamed, because it is a string value
      Object.defineProperty(v, '_registry', {
        value: a,
        writable: !1
      });
      return a
    },
    configurable: !0
  }
});
```

That will cause `TypeError: Cannot redefine property: _registry` on second access of `v.m`;

That is not a problem with references to itself:
```
Target.JSRoyale = new Target('JSRoyale');
Target.JS = new Target('JS');
Target.JSNode = new Target('JSNode');
Target.JSNodeModule = new Target('JSNodeModule');
Target.SWF = new Target('SWF');
```

That was not a problem on 0.9.6 since `static const` and `static var` was initialized without properties, just like regular members:

```
Enum._registry = new EnumRegistry();
```

I created a minimal project reproducing the issue at [repo](https://github.com/mrchnk/royale-compiler-problems/tree/master/static-initialization)

I wanted to mention one more problem with such initialization on larger codebases.
Seems like that lazy-initialization reference to EnumRegistry is not counted properly during compilation. 
And that can cause EnumRegistry class is not fully initialized during another static initialization (like Target.* const's)

**Comment by mrchnk** [comment]
I think a simple solution could be replace `Object.defineProperty` by `Object.defineProperties`
```
Enum.get___registry = function() {
  var value = new EnumRegistry();
  Object.defineProperties(Enum, {
    _registry: { 
      value: value, 
      writable: false 
    }
  });
  return value;
};
```
somewhere at
https://github.com/apache/royale-compiler/blob/6f75df78d08d3c4a7f81a8d25d96b978972ee480/compiler-jx/src/main/java/org/apache/royale/compiler/internal/codegen/js/jx/FieldEmitter.java#L220-L228

**Comment by joshtynjala** [comment]
Thanks for the great bug report! Your suggested solution works very nicely.

**Comment by carlosrovira** [comment]
cool! Thanks! :)
