### ISSUE TITLE
AMF under JS is missing functionality - fixes offered

### ISSUE THREAD

**Issue by SemiConscious** [apache/royale-compiler#171]
I am working on porting a flex app to royale. I have come across an issue in the AMF implementation which I think would be worth fixing in the SDK.

problem 1: Our existing implementation depends heavily on the use of the target URI. In the current implementation this is not passed down to `AMFNetConnection`, and is always null. I think this is a fairly key part of AMF which needs to be right, and it's easy to fix.

problem 2: It's also key to us to pass an array of optional parameters (the 3rd parameter in `NetConnection.call()`) - think of it as parameters which behind the scenes are used to make further REST API calls to our platform's core API, which I understand to be a fairly common use case,. In the existing implementation, the params parameter in `NetConnection.call()` is an `IMessage`. `NetConnection.call(`) calls `AMFNetConnection.call(`) with an `...` parameter. This combination results in being unable to deliver a flat 1 dimensional array to AMF. You end up with either the array you want to send with all but the first member truncated, or an array of arrays with 1 member. This doesn't model what was previously there in flex/AMF.

I don't know how much you really care about flex compatibility beyond a certain point, but for what it's worth I have a branch with fixes for these which I could commit to the main repo, so you can take a look.

What a fantastic job you guys have done! I have been working on this for 4 weeks solid and this is the first issue I haven't been able to conveniently work around. Well done, and happy new year!

**Comment by carlosrovira** [comment]
Hi and thanks your words and reporting. 
Royale is open to patches. In fact as an Apache project is managed by all of us, and you can be part of it. So if you have fixes for that, please submit a PR (Pull Request) so others can review, approve and merge. Will be happy to do that. For this, maybe @greg-dove is the best to check your fixes.
Thanks!

**Comment by SemiConscious** [comment]
Hey Carlos - thanks. I dont seem to have permission to commit my branch to
the repo - should i submit an old school patch instead?
Best, Jim

**Comment by carlosrovira** [comment]
Hi, no. Github has PRs (see here https://royale.apache.org/get-involved and https://github.com/apache/royale-compiler/pulls)
That's a great tool since you can work in your fork and then submit a PR to the project so we can review and integrate. There's lots of tutorials on how to do a PR over the internet, check any one to see the steps :)

**Comment by SemiConscious** [comment]
Ok I see. I have created a pull request https://github.com/apache/royale-asjs/pull/1023. By the way I should have created the issue under the royale-asjs repo not the royale-compiler! Sorry about that.

I can't immediately see how to mark the pull request for @greg-dove's attention. Sorry again if this as an obvious query but there's a first time for everything.

**Comment by carlosrovira** [comment]
Hi,

yeah, right, I guess that PR will not be valid if is from other project...or maybe not.
I think we pointed Greg from both threads so if he's not on vacation he probably is notified.
I commented already on the PR itself. Thanks again! :)

**Comment by SemiConscious** [comment]
Addressed in https://github.com/apache/royale-asjs/pull/1056
