### ISSUE TITLE
"For each" Sometimes outright fails silently

### ISSUE THREAD

**Issue by brianraymes** [apache/royale-compiler#185]
"For each" is sporadically unusable as it doesn't seem to actually loop over values in many cases (for currently unknown reasons).

**Steps to Reproduce**

Have a for each that should loop over each value in an ArrayList:

```
for each (var thing:SomeObject in this.someOtherObject.someArrayList)
    // do something with thing
```
**Expected Results**

The "for each" retrieves each value in the list.

**Actual Results**

The above may work as expected, find one object in the list, or none all together. This is consistent between builds, as-in, when I find a case that doesn't work, it never seems to work. In this case, the following workaround is always successful.

**Workaround**

```
for (var i:int = 0; i < this.someOtherObject.someArrayList.length; i++)
{
    var thing:SomeObject = this.someOtherObject.someArrayList.getItemAt(i) as SomeObject;
    // do something with thing
}
```

**Comments**

This seems rather severe as there doesn't appear to be any warning, error, or any other useful information to identify what is going wrong. Hopefully this is as consistent as I've seen, so I don't have unexpected outcomes in later builds beyond test and deployment.

**Comment by greg-dove** [comment]
When you are doing this is it clear to the compiler that the ArrayList instance being targeted is strongly typed?

So, for example, with the
`this.someOtherObject.someArrayList`
in:
`for each (var thing:SomeObject in this.someOtherObject.someArrayList)`

is `this.someOtherObject ` a strongly typed member, where it's type has a strongly typed member named 'someArrayList' which is typed as ArrayList (or iirc the interface behind ArrayList is supported as well).

Why I ask: If there is any untyped (e.g. public var someOtherObject:Object) path to the for each target, then the compiler cannot know to apply the rules for iteration over ArrayList.

If the above is happening, you could perhaps try the following hard casting:
`for each (var thing:SomeObject in ArrayList(this.someOtherObject.someArrayList))`

**Comment by brianraymes** [comment]
Almost everything I work with is strongly typed. That's what has had me so confused about this issue. I rarely use, and generally try to stay away from, non-typed variables.

Here is what is further perplexing. In general, it has stayed pretty consistent. Once I see that it isn't working, it generally stays that way so I revert to the old `(for i = 0..)` approach. I tried hard casting and it worked, took it out, and it's still working.. so the consistency is no more in this case.

The next time I see this happen, I'll take a look at the generated JavaScript and compare to see if I can determine what is potentially going on from that perspective. I have plenty of other places in my codebase where I've had to use the legacy approach. I'll experiment and report back.

**Comment by brianraymes** [comment]
Ha! I believe I found the issue... and the above appears to be a side affect to the actual issue.

The following code is converted incorrectly to javascript. Notice that I do not have `{ }` surrounding the line following the `for each loop`.

```
for each (var thing:SomeObject in this.someOtherObject.someArrayList)
    thing.doSomething();
```

The output for this in javascript is basically the following:

```
for (var /** @type {*} */ royale$for$Each$Iterator0 = org.apache.royale.language.iterator.arrayLike(this.someOtherObject.someArrayList, 'length', 'getItemAt', false); royale$for$Each$Iterator0['hasNext']();)
    var /** @type {path.to.SomeObject} */ key = /* implicit cast */ org.apache.royale.utils.Language.as(royale$for$Each$Iterator0['next'](), path.to.SomeObject, true);
    thing.doSomething();
```

Notice that the first line sets the loop variable and the second line is no longer within the the scope of the for loop. This is why I'd sometimes see only one pass through the for loop, even though the debugger would show me that there were many more.

Simply adding `{ }` like so:

```
for each (var thing:SomeObject in this.someOtherObject.someArrayList) {
    thing.doSomething();
}
```

Creates the correct output:

```
for (var /** @type {*} */ royale$for$Each$Iterator0 = org.apache.royale.language.iterator.arrayLike(this.someOtherObject.someArrayList, 'length', 'getItemAt', false); royale$for$Each$Iterator0['hasNext']();) {
    var /** @type {path.to.SomeObject} */ key = /* implicit cast */ org.apache.royale.utils.Language.as(royale$for$Each$Iterator0['next'](), path.to.SomeObject, true);
    thing.doSomething();
}
```

_This all being said, I've definitely noticed other inconsistencies where I could have definitely used the surrounding curly braces and it has still failed. I'll have to evaluate those independently to see what could be going wrong there._

**Comment by greg-dove** [comment]
Thanks, that is very helpful. I will look into this during the coming week and address it!

**Comment by Laturine** [comment]
To add to this. having a cast in the forEach declaration will cause incorrect javascript to be created.
For instance. 
for each (var ac:ArrayCollection in obj.List as ArrayCollection) {} //the Work Around was to pull the cast outside

**Comment by greg-dove** [comment]
I had hoped to look into this today, but I am out of time. I will find some time tomorrow to take a look. 
@Laturine The ArrayCollection issue is not the same as the ArrayList issue but I will try to get to that also if I can.

**Comment by greg-dove** [comment]
@brianraymes the latest code in the compiler should address that issue you described.

@Laturine I will have the fix for ArrayCollection coercion  `something as ArrayCollection` and also `ArrayCollection(something)` in tomorrow.

**Comment by brianraymes** [comment]
Fantastic. Thank you @greg-dove ! Most appreciated.

**Comment by greg-dove** [comment]
@Laturine the support for iteration over ArrayCollection (and Proxy-based instances in general) should be more robust following a recent compiler commit. 
Example fixes:
`for each (var thing:Object in something as ArrayCollection)`
`for each (var thing:Object in ArrayCollection(something))`
`for each (var thing:Object in aMethodThatReturnsAnArrayCollection())`

the above were not working, but now should be (with new compiler build)

and also null safety:
var myNullReference:ArrayCollection = null;
`for each (var thing:Object in myNullReference)`
the above was throwing a runtime error, but now should not be (it skips the loop body, as it should, with new compiler build)

**Comment by brianraymes** [comment]
Oh, that's fantastic. I was going to report the null issue as well. It's another case where the exceptions seem to be swallowed and subsequent code fails to execute at runtime. I keep thinking bindings have been failing for weird reasons, when in fact, I am finding that non-caught and non-erroring NPEs are stopping execution without any warning or error.

**Comment by greg-dove** [comment]
> Oh, that's fantastic. I was going to report the null issue as well. It's another case where the exceptions seem to be swallowed and subsequent code fails to execute at runtime. I keep thinking bindings have been failing for weird reasons, when in fact, I am finding that non-caught and non-erroring NPEs are stopping execution without any warning or error.

@brianraymes it was definitely a possibility. For iteration over royale collections-based ArrayList it should be null-safe, if you see examples where it is not, please create an issue and I will work to address it. The ArrayCollection example is different because the way the code output for the loop is generated is different. At some point I will investigate whether it makes sense to use the same approach as ArrayList, because at the moment the Royale (non-mx) ArrayList for-each iteration is objectively more robust in situations when the loop target is mutated (e.g. its length is reduced or increased, for example) inside the loop. Usually this does not happen inside the loop, but at the moment both XMLList iteration and mx ArrayCollection iteration rely on it **not** happening inside the loop in order to behave correctly. 
On that note, XMLList for-each iteration also probably does not yet survive a null loop target at this point. I will check this sometime in the next week and see if it needs the same treatment as Proxy-based (of which ArrayCollection is one example) classes. So this may not yet work (it may throw runtime error):
```
var myNullReference:XMLList = null;
for each (var thing:XML in myNullReference)
```

In terms of bindings... bindings do often have phases where they can have errors during startup  (and usually then succeed on future executions when there are no null safety related errors) and these startup attempts with errors are 'swallowed' so they should not stop execution. Generally with Royale there are less of these than was the case in Flex, but the intention is that the execution thread should still proceed. If you can create or share small examples where execution is stopping unexpectedly, I would be happy to look into those to try to figure that out.

**Comment by brianraymes** [comment]
Here is an example:

```
private var _config:SomeTypedObject;

[Bindable]
public function get config():SomeTypedObject
{
    return this._config;
}

public function set config(SomeTypedObject):void
{
    this._config = value;

    // Do something that causes an NPE. In this case, someProperty is null.
    warning = config.someProperty.length == 0;
}
```

In this scenario, sub properties of config is bound to various fields. Because of the NPE, none of the bindings for this field fire, even though the value is set before the NPE. No error appears in the console or debugger. It's as if it's caught and suppressed at runtime.

Now that I think about it, it may be about how the compiler converts generic `[Bindable]` fields to dispatch the updated event. I'm betting in this case, if I were to use my own event name and dispatch before the NPE, it would probably work.

**Comment by greg-dove** [comment]
@brianraymes I have copied your last comment to start #188
