### ISSUE TITLE
No error when calling non-existent super method

### ISSUE THREAD

**Issue by Harbs** [apache/royale-compiler#19]
I just discovered a bug in my code where I was calling `super.swapElementsAt(fIdx,npIdx);` `swapElementsAt()` was only defined in the class and not the super-class. The code compiled without errors and only failed when the code: `superClass_.swapElementsAt.apply(this, [ fIdx, npIdx] );` was run and produced a RTE of `TypeError: Cannot read property 'apply' of undefined`

I need to include a test case to reproduce this, but I wanted to capture the issue before I forget.

**Comment by joshtynjala** [comment]
Closing because it was fixed in 660fff90b3daae204794dcbc3762c2e7471803eb
