### ISSUE TITLE
Unable to parse valid XML with CDATA

### ISSUE THREAD

**Issue by Harbs** [apache/royale-compiler#22]
The following code:
````
var content:XML =
<root>
	<content><![CDATA[<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.3-c011 66.145661, 2012/02/06-14:56:27        ">
   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Description rdf:about=""/>
   </rdf:RDF>
</x:xmpmeta>
<?xpacket end="r"?>]]></content>
</root>;
````

Produces an error in the compiler:
````
Syntax error: 'content' tag (or tag before this tag, or non-tag inside this tag) is unclosed or tag not allowed here.
    [mxmlc]
    [mxmlc] <?xpacket end="r"?>]]></content>
    [mxmlc]                       ^
 ````
Removing CDATA makes the error go away:
````
var content:XML =
<root>
	<content><?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.3-c011 66.145661, 2012/02/06-14:56:27        ">
   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Description rdf:about=""/>
   </rdf:RDF>
</x:xmpmeta>
<?xpacket end="r"?></content>
</root>;
````

**Comment by Harbs** [comment]
Interestingly this also produces an error:
````
var content:XML = new XML(
'<root>' +
'	<content><![CDATA[<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>' +
'<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.3-c011 66.145661, 2012/02/06-14:56:27        ">' +
'   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">' +
'      <rdf:Description rdf:about=""/>' +
'   </rdf:RDF>' +
'</x:xmpmeta>' +
'<?xpacket end="r"?>]]></content>' +
'</root>');
````
Separating the two right brackets makes the error go away:
````
var content:XML = new XML(
'<root>' +
'	<content><![CDATA[<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>' +
'<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.3-c011 66.145661, 2012/02/06-14:56:27        ">' +
'   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">' +
'      <rdf:Description rdf:about=""/>' +
'   </rdf:RDF>' +
'</x:xmpmeta>' +
'<?xpacket end="r"?>]'+']></content>' +
'</root>');
````
Hopefully this is helpful in tracking down the source of the problem.

**Comment by Harbs** [comment]
It appears that this is only a problem in an MXML file. The same code in an AS file compiles correctly.

**Comment by greg-dove** [comment]
Isn't this because the mxml file is xml, and the closing cdata tag encountered in the script block is the 'closing' tag for the script block's cdata? I am pretty sure these cannot be nested, so it needs to be not recongnised as a closing 'tag' for cdata when parsed.

**Comment by Harbs** [comment]
That is my suspicion.

However, I would have thought that at least the quoted text should have worked. I don't see why even the literal should not be parseable considering it's in a variable declaration.

I'm OK if we come to the conclusion that this is an acceptable limitation, but it would be nice if we'd at least document it.

**Comment by aharui** [comment]
Does it work in the Flex compiler?

**Comment by Harbs** [comment]
No, but the error is much more descriptive. In Flex you get this error:
`The element type 'fx:Script' must be terminated by the matching end-tag '</fx:Script>'.`

In Royale, the error is:
`'content' tag (or tag before this tag, or non-tag inside this tag) is unclosed or tag not allowed here.`

**Comment by Harbs** [comment]
I guess both errors are not completely descriptive of the problem. I'm not sure how much effort this is worth...

**Comment by Harbs** [comment]
I'm just closing this issue. I think we can call it an acceptable limitation.
