### ISSUE TITLE
The ASF Jenkins build hangs exhausting resources

### ISSUE THREAD

**Issue by Tibor17** [apache/royale-compiler#23]
Please check all your Jenkins CI builds because the one [1] hangs or is doing something 3 days.
It is not clear what it does because the logs [2] are so huge (96GB) that Jenkins does not want to show the tail.
[1]: https://builds.apache.org/job/Royale%20Pipeline/
[2]: https://builds.apache.org/job/Royale%20Pipeline/job/feature%252Fvivid-ui-set/2/console

**Comment by aharui** [comment]
Last build seemed to pass after removing the -X option.  Not sure if it was really that or not.  But there was a ton of output about downloading the huge Adobe AIR SDK so maybe having all of that extra debug output really did overwhelm resources.
