### ISSUE TITLE
CSS support [type=xxx]

### ISSUE THREAD

**Issue by mjesteve** [apache/royale-compiler#238]
The sass-maven-plugin is no longer maintained. This plugin is tested and verified in the Royale project but I think it would be interesting to move forward. I have been testing the dart-sass-maven-plugin and I think it is a valid and stable option.

The tests I have carried out have been satisfactory but I have found problems with the styles applicable to specific "types":
`input[type="checkbox"]`
In these cases, the dart-sass plugin generates the CSS as `input[type=checkbox]` and this is not valid for royale-compiler.

Would it be convenient to include this possibility in our compiler?

Thx

**Comment by joshtynjala** [comment]
According to the CSS specification:

> Attribute values must be identifiers or strings.

Source: https://www.w3.org/TR/CSS2/selector.html#attribute-selectors

In the case of `input[type=checkbox]`, `checkbox` is considered a valid identifier, so we should ideally support it.

Related notes about identifiers.

> In CSS, identifiers (including element names, classes, and IDs in [selectors](https://www.w3.org/TR/CSS2/selector.html)) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" > may be written as "B\&W\?" or "B\26 W\3F".
> 
> Note that Unicode is code-by-code equivalent to ISO 10646

Source: https://www.w3.org/TR/CSS2/syndata.html#value-def-identifier

**Comment by mjesteve** [comment]
@Josh, "I have tried it" jajajaja :P 
I've been looking at the code and your indications ( attribute-selectors, identifier) and I think I've identified ....
(CSS.g)
![image](https://github.com/apache/royale-compiler/assets/55754195/d0b1b2ca-3598-49ab-9295-bd510e8c799a)

To support identifiers in attributeSelector would we have to do something like this?

```
attributeValue
    :    STRING
    |    ID
    ;
```
ó
 ```
attributeSelector
    :   SQUARE_OPEN attributeName attributeOperator* (attributeName | attributeValue*) SQUARE_END
    ;
```
CSSTree.g
I identify these blocks:

![image](https://github.com/apache/royale-compiler/assets/55754195/2d898ab5-9335-471e-8342-4ff791b6b0bd)

Is it the good direction?

Bear with me :P 
Now I'm looking at what the ".g" files are :P

**Comment by mjesteve** [comment]
@Josh I have made some changes that work for me. [d347bf7](https://github.com/apache/royale-compiler/commit/d347bf7fa57dd9d67cb83401d3db06ce925a661c)
I have compiled the SDK and then compiled my sass projects and have not had any problems.
I don't know if the changes are correct or if they are incomplete or have errors, could you look at them?

Thx.

**Comment by mjesteve** [comment]
False positive. I don't know why, "today", when doing a complete compilation (I did it the other day several times) it compiles, it doesn't give an error, but the code generated by the compiler in App.js is not correct:

![image](https://github.com/apache/royale-compiler/assets/55754195/0b46c28a-d3aa-4846-ac18-8da49ac803cd)

For it to work, the double quotes must be single:

![image](https://github.com/apache/royale-compiler/assets/55754195/917ccb60-4fbe-4f19-a251-3cf396e89c0a)

I'm missing the second part of the modification. I have modified the lexer, right? and now the transpilation part is missing?
I'm going to continue investigating...

**Comment by joshtynjala** [comment]
> it doesn't give an error, but the code generated by the compiler in App.js is not correct

I can reproduce this issue, even without your changes. It's an existing bug. I've committed a fix.

**Comment by joshtynjala** [comment]
@mjesteve Commit d347bf7fa57dd9d67cb83401d3db06ce925a661c looks good to me. Go ahead and merge it into develop.

**Comment by mjesteve** [comment]
I will incorporate your changes and test it before confirming.
Thx Josh
