### ISSUE TITLE
SWC's CSS Name needs to be named "defaults.css" mandatorily

### ISSUE THREAD

**Issue by carlosrovira** [apache/royale-compiler#27]
I tried to create a .css in a library with a different name than "defaults.css". When used the library in a final application, the css although included in pom.xml and in the final .swc is not processed in the application, so there's no css rules of that.

Seems something has change in lasts days and now only "defaults.css" is allowed as a name.
Is that right?

**Comment by aharui** [comment]
Themes will have every .css file applied, but regular component SWCs only have a default.css.
