### ISSUE TITLE
selectors without initial dot are removed from final css

### ISSUE THREAD

**Issue by carlosrovira** [apache/royale-compiler#32]
Hi,

this:

.jewel.slider input[type="range"] {...}

or even this

input[type="range"] {...}

are removed from the final css

This is other bug in compilation of css that needs to be addressed to continue con certain tasks in theme feature

thanks

**Comment by aharui** [comment]
I think this is fixed

**Comment by carlosrovira** [comment]
Hi Alex,
just tried and this solved all this problems thanks! :)
