### ISSUE TITLE
content: url fails to compile

### ISSUE THREAD

**Issue by carlosrovira** [apache/royale-compiler#34]
Hi,

while

`content: "Hello";`

is compiled right, this other:

`content: url(assets/checkbox-tick.svg);`

Fails with the following error:

Internal error: java.lang.ClassCastException: org.apache.royale.compiler.internal.css.CSSURLAndFormatPropertyValue cannot be cast to org.apache.royale.compiler.internal.css.CSSStringPropertyValue org.apache.royale.compiler.internal.css.CSSProperty.toCSSString(CSSProperty.java:77)

I'll try to do this in other way, but for now it seems the best way to create the tick in a checkbox via svg. Tested modifying the CSS live on the browser works great. Hope you could fix this

Thanks

**Comment by Harbs** [comment]
You are missing quotes in the url var. It should be something like this:
`content: url('assets/checkbox-tick.svg');`

**Comment by Harbs** [comment]
That said, it could be the error should be more descriptive...

**Comment by Harbs** [comment]
Hmm. It seems like unquoted urls are allowed in HTML CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/url

**Comment by carlosrovira** [comment]
Right, in fact we need to support unquouted, since this is related to bug #35
I'm think I solved it in compiler, but now don't know how to handle it in SimpleCSSValuesImpl, since it seems it expects to have the quotes, but don't know where is processed. At least with my fix in the compiler branch there's no error, but it's not working ok

**Comment by carlosrovira** [comment]
But regarding you proposed solution I tried to use it with quotes and it doesn't work.

**Comment by carlosrovira** [comment]
Hi Alex, This is working now, thanks!
