### ISSUE TITLE
Selector element with "+" crash 

### ISSUE THREAD

**Issue by carlosrovira** [apache/royale-compiler#37]
If I have this a element + .classname rule like this

```
dialog + .backdrop {
  background-color: red;
}
```

The final App crashes in the following way:

/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/JewelTheme-0.9.3-SNAPSHOT-js.swc:defaults.css(1): col: 1 Error: CSSTree.g: node from line 0:0 required (...)+ loop did not match anything at input 'dialog'

/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/JewelTheme-0.9.3-SNAPSHOT-js.swc:defaults.css(1): col: 1 Error: CSSTree.g: node from line 0:0 required (...)+ loop did not match anything at input 'dialog +'

/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/JewelTheme-0.9.3-SNAPSHOT-js.swc:defaults.css(57): col: 8 Error: JewelTheme-0.9.3-SNAPSHOT-js.swc:defaults.css line 56:7 no viable alternative at input '+'

**Comment by carlosrovira** [comment]
Hi Alex,

I see this working if I put on final app example project but, if I put on library css I get this:

/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/Jewel-0.9.3-SNAPSHOT-js.swc:defaults.css(96): col: 2 Error: Type selector without namespace prefix requires a default namespace to be defined. input


/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/Jewel-0.9.3-SNAPSHOT-js.swc:defaults.css(96): col: 2 Error: Type selector without namespace prefix requires a default namespace to be defined. input


/Users/carlosrovira/Dev/Royale/Source/royale-asjs/examples/royale/JewelExample/Jewel-0.9.3-SNAPSHOT-js.swc:defaults.css(96): col: 2 Error: Type selector without namespace prefix requires a default namespace to be defined. input

(I think something similar could be happening with #33)

**Comment by aharui** [comment]
HTML Elements like "input" need to be in the "http://www.w3.org/1999/xhtml" namespace

**Comment by carlosrovira** [comment]
I have this two in the css:

`@namespace j "library://ns.apache.org/royale/jewel";
@namespace "http://www.w3.org/1999/xhtml";`

**Comment by carlosrovira** [comment]
Maybe I need to add some prefix?

```
@namespace x "http://www.w3.org/1999/xhtml";

x|input + .some {
...
}
```

**Comment by aharui** [comment]
The code that emits this error should be CSSSemanticAnalyzer in the resolveSelectors method where it creates a CSSUnknownDefaultNamespaceProblem.  Add some debugging output around that code and see why.  It looks like it thinks that the CSS file doesn't have a @namespace without a prefix that specifies the default namespace.

Maybe dump the SWC and see what defaults.css is actually in the SWC.

**Comment by Harbs** [comment]
Does placing the default namespace first make a difference?
