### ISSUE TITLE
GoogleDepsWriter NullPointerException

### ISSUE THREAD

**Issue by kennylerma** [apache/royale-compiler#47]
BUILD# 1086

Looking at the GoogleDepsWriter class, line 100 is calling visited.clear();
However, the visited variable is not created until line 248.  Not certain if this is the problem, but seems plausible.

Internal error: java.lang.NullPointerException org.apache.royale.compiler.internal.graph.GoogDepsWriter.getListOfFiles(GoogDepsWriter.java:100)org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyalePublisher.publish(MXMLRoyalePublisher.java:376)org.apache.royale.compiler.clients.MXMLJSCRoyale.compile(MXMLJSCRoyale.java:384)org.apache.royale.compiler.clients.MXMLJSCRoyale._mainNoExit(MXMLJSCRoyale.java:240)org.apache.royale.compiler.clients.MXMLJSCRoyale.mainNoExit(MXMLJSCRoyale.java:197)org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:345)org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:281)org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:240)org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:222)

64.68937496 seconds
Build halted with errors.

**Comment by aharui** [comment]
Line 248 is a class initializer so visited should be created at instantiation and before any APIs are called.  What are the options being passed to the compiler and what is the entire console output leading up to the exception?

**Comment by kennylerma** [comment]
Ahh, you're correct.  Makes sense.  I found I'm getting a "No GoogDep" right before the error.  This happens with -remove-circulars set to true which is default.  If I set it to false, it builds without errors.

[Output-RemoveCircularsError.txt](https://github.com/apache/royale-compiler/files/2163696/Output-RemoveCircularsError.txt)

**Comment by aharui** [comment]
I can't explain why it is saying line #100 is at fault.  What version of Royale are you using?

But anyway, the NPE is because we don't catch errors when a dependency can't be found, in this case createjs.EventDispatcher.  It looks like you have your own CreateJS.swc, Should it have a createjs.EventDispatcher?  Looks like a SoundManager class is dependent on it.

**Comment by kennylerma** [comment]
I'm using build #1086 from Jenkins
http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/1086/

I am indeed using my own CreateJS.swc.  I'll have a look at my SoundManager class and see if I can find anything.  Thanks for looking into this.

**Comment by kennylerma** [comment]
I corrected the issue in my code, but this may be a problem overall.  I found instantiating a new class instance from a class in a SWC on a static variable was causing the issue.  So, I moved the instance creation inside a method to correct the error.  The CreateJS.swc I created is an as3 api only and doesn't include javascript in the swc, so perhaps that's the reason?

Below is what caused my error.

`private static var _dispatchObject:EventDispatcher = new EventDispatcher();`

**Comment by aharui** [comment]
I altered one of the examples to add that line of code and it compiled without errors.

GoogDepsWriter is going around looking for JS files for classes required by other JS files.  EventDispatcher (if it is org.apache.royale.events.EventDispatcher) should be in Core.swc, but if you referenced some other EventDispatcher and it was in your CreateJS.swc and there was no JS file for it, it could cause a problem in GoogDepsWriter, but I'm not sure it should have made a difference if you created the EventDispacher in the static initializer or not.  Referencing a class in a static initializer does affect GoogDepsWriter.  It will give priority when removing circulars to classes referenced in static initializers, but at some other point, it should have gone looking for EventDispatcher and successfully find it in Core.swc, or fail to find its JS file.

**Comment by kennylerma** [comment]
Sorry, I wasn't clear earlier.  I used createjs.EventDispatcher.  My CreateJS.swc is just a skeleton of classes and it's used as an external-library.  So, the compiler should not try to include and classes in the built output.  The CreateJS.swc works just fine except in the instance below.  I attached my swc for reference.
[CreateJS.zip](https://github.com/apache/royale-compiler/files/2333376/CreateJS.zip)

`private static var _dispatchObject:EventDispatcher = new createjs.EventDispatcher();`

**Comment by aharui** [comment]
Ah, ok.  I think then that the issue may be that we weren't checking if classes used in static initializers were external or not.  I just pushed a change for that.  If the nightly builds pass you can get a newer compiler that way or grab a nightly build of the compiler and replace the jars.

**Comment by kennylerma** [comment]
Awesome!  Thanks @aharui !  I'll check it out once the build passes.

**Comment by kennylerma** [comment]
That fixed it!  Great work @aharui

**Comment by aharui** [comment]
Is StaticClass in your source path, or some external dependency?

**Comment by kennylerma** [comment]
@aharui StaticClass is indeed in my source path.  I'm seeing the issue with other projects where the error states that the method is not a constructor.  So, basically anywhere a class is instantiated on a static variable.

**Comment by kennylerma** [comment]
@aharui Do you think this can get fixed before the next release?  This breaks all of SpriteFlexjs unfortunately.  This would prevent me from pushing a new update to SpriteFlexjs until this is corrected.

**Comment by aharui** [comment]
Oh yeah, I knew I was forgetting something.  I will look into it now.

**Comment by aharui** [comment]
AFAICT, this error wasn't cause by the above commit.  It just allowed you to get further to the point where you would run into this issue.  I'm surprised we didn't hit this sooner.  The main class's dependencies were not being added to the addDependency list.  The only reason it worked is because those same dependencies were referenced elsewhere in the code other than the static dependency list.  I am testing a fix now.

**Comment by carlosrovira** [comment]
@kennylerma don't worry about to reach this release, we have still many things to do. My advice is to get your development environment running with the actual repo code so you can work in SpriteFlexJS and prepare a PR. For that you need to prepare the library and setup maven for the project. We'll help you when you reach that point ;).

**Comment by kennylerma** [comment]
@carlosrovira yeah I mainly want to be able to generate some videos using Royale and SpriteFlexjs and I would like to direct people to the latest royale release and have it work correctly.  So, that's the main reason, but it looks like @aharui may have resolved it already.  I'll start looking at what is needed to add Spriteflexjs into Royale very soon.

**Comment by carlosrovira** [comment]
Hi Kenny that's great. In case you find something is not in a released SDK you can always point the users that "the feature will shio in forthcoming SDK x.x.x", that's the strategy I took for Jewel that is still unreleased in an official SDK version. In the other hand, we decided to release as often as possible, and more reasons is if you bring some new functionality like spriteflexjs to the plate. I think we should not be too late in release a other version with that. thanks.
