### ISSUE TITLE
compiler binding removes latest ' 

### ISSUE THREAD

**Issue by carlosrovira** [apache/royale-compiler#49]
This line of code

`<j:Label text="textinput.width='{textinput.width}'"/>`

outputs this:

`<div class="jewel label">textinput.width='0</div>`

removing the last '

I think is a compiler issue, but maybe could be something related to binding in the framework?

**Comment by carlosrovira** [comment]
Another point is that output is intialized to 0, but text input width is 211

**Comment by carlosrovira** [comment]
I close this by accident

**Comment by joshtynjala** [comment]
Confirmed that this issue still exists in 0.9.7 nightlies.

This following code correctly outputs the "s" character, so it seems to be handling the end quote incorrectly.

```mxml
<j:Label text="textinput.width='{textinput.width}s"/>
```

This also fails, and produces invalid code:

```mxml
<j:Label text='textinput.width="{textinput.width}"'/>
```

In case I need to review this again in the future, here's the current JS output of all three.

Bug! Missing ' character:

```js
function() { return "textinput.width='" + this.textinput.width; }
```

Correct:

```js
function() { return "textinput.width='" + this.textinput.width + "s"; }
```

Bug! unescaped " character:

```js
function() { return "textinput.width="" + this.textinput.width; }
```

**Comment by carlosrovira** [comment]
Thanks for fixing this Josh! :)
