### ISSUE TITLE
declaring mx:methods in one mx:RemoteObject make other RemoteObjects fail

### ISSUE THREAD

**Issue by carlosrovira** [apache/royale-compiler#53]
In this example: https://github.com/apache/royale-asjs/tree/develop/examples/mxroyale/RemoteObjectAMFTest

serviceResp fails with the following error:

```
 [Error] TypeError: undefined is not an object (evaluating
    'this.serviceResp.getProperty')
    sendEcho (App.js:269)
    $EH3 (App.js:321)
    (función anónima)
    fireListener (events.js:744)
    fireListenerOverride (HTMLElementWrapper.js:61)
    handleBrowserEvent_ (events.js:870)
    (función anónima) (events.js:289)
```

But if comment the mx:method section of the "service" RemoteObject like this:

```
<!-- <mx:method name="echo">
    <mx:arguments>
    <symbol>{name_txt.text}</symbol>
    </mx:arguments>
    </mx:method>
    <mx:method name="getObjectArray1">
    </mx:method>
    <mx:method name="getSomeProduct">
    </mx:method> -->
```

Then serviceResp works right.

I figure the problem is in compiler and once a RO has mx:method declared the rest must have the same. But I can ensure this is the real problem.

**Comment by aharui** [comment]
For some reason, when Operations are declared in MXML, the next RemoteObject doesn't appear in the output at all.
