### ISSUE TITLE
Dependency error when extending class and implementing interface from "external" SWC library

### ISSUE THREAD

**Issue by kennylerma** [apache/royale-compiler#57]
The included TEST.swc has a simple TestClass class and IContent interface in it.  The swc is compiled correctly and includes the javascript.  When I use the swc as an "Included" library it works just fine.  However, if I use the swc as an "External" library so not to include the classes in the output, I get the error below.  The key here is that I'm extending a class from the swc and implementing and Interface "IContent".  Extending a class from the swc seems to work fine, but when I also implement an Interface from a swc I get the below dependency error.

No GoogDep for IContent
Internal error: java.lang.RuntimeException: Unable to find dependency information for class: IContent org.apache.royale.compiler.internal.graph.GoogDepsWriter.sortFunction(GoogDepsWriter.java:401)org.apache.royale.compiler.internal.graph.GoogDepsWriter.sort(GoogDepsWriter.java:289)org.apache.royale.compiler.internal.graph.GoogDepsWriter.getListOfFiles(GoogDepsWriter.java:105)org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyalePublisher.publish(MXMLRoyalePublisher.java:421)org.apache.royale.compiler.clients.MXMLJSCNative.compile(MXMLJSCNative.java:384)org.apache.royale.compiler.clients.MXMLJSCNative._mainNoExit(MXMLJSCNative.java:234)org.apache.royale.compiler.clients.MXMLJSCNative.mainNoExit(MXMLJSCNative.java:191)org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:401)org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:300)org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:259)org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:241)

I'm using the last successful BUILD: 1856

Main document class
```
package
{
    import TestClass;
    import IContent
	
    public class Main extends TestClass implements IContent
    {	
		
        public function Main()
        {
			
        }
    }
}
```

Class from TEST.swc
```
package 
{
    public class TestClass
    {
        public function TestClass() 
	{
			
	}
    }
}
```

Interface from TEST.swc
```
package
{
    public interface IContent
    {
	function destroy():void;
    }
}
```

[TestFiles.zip](https://github.com/apache/royale-compiler/files/2566986/TestFiles.zip)

**Comment by aharui** [comment]
Interesting.  The interface shouldn't be in the requires list.  But after we fix that, there will be other warnings because Google Closure Compiler cannot find the base class and interface which are referenced by some of the code.  A typedefs/externs file is required for that, and I don't think you can use the .js files for the external class and interface as the typedef/extern.  So that means, unlike a SWF class, which can be used as the external or linked definitions, the .js class cannot.  It would be rather heavy to generate a sister typedef file for every .js file since most classes probably won't be used as external dependencies.  Maybe in the future we can teach the compiler to autogenerate a typedef/extern on the fly if it sees that there are external references that have .js files that aren't externs.  But that could be slow.

**Comment by kennylerma** [comment]
Thanks @aharui.  I have a work-around, but it's not very elegant.  I have a large project that loads many separate projects from a menu.  It's just like loading SWF files.  Each project shares the same base classes, so I need to exclude those base classes in each project and create a separate javascript file to use as the base library for all projects.  This way I don't load the same classes again and cause conflicts.  I do this by using the --externs argument for the closure compiler as below in a batch file.  I make a debug build and then use the closure compiler to combine the js files, but exclude the classes in the extern file.  Perhaps there could be a way to generate the single js extern file in the compiler when generating swcs.

```
@echo off
set ARGS=--externs ../../../BaseClasses.js
set ARGS=%ARGS% --js bin\js-debug\com\test\*.js
set ARGS=%ARGS% --js bin\js-debug\com\test\test_Main.js
set ARGS=%ARGS% --dependency_mode=STRICT --entry_point=test_Main
@echo on
java -jar %1/js/lib/google/closure-compiler/compiler.jar %ARGS% --compilation_level WHITESPACE_ONLY --js_output_file=test_Module.js
```

**Comment by aharui** [comment]
You should be able to pass these options to GCC via the Royale compiler.  I think the syntax would be:

-js-compiler-option="--externs ../../../BaseClasses.js"

**Comment by aharui** [comment]
I think we should be able to add an "Externs" compiler target (like we have for SWF and JSRoyale and more) that will use a different set of Emitters and generate externs.  The compiler can generate externs from AS files already, but it assumes the AS is written as an extern (no method body).  The Externs emitters would need to strip function bodies.

Since you have a  workaround, I will probably get the next release out before working on it, but you or someone else are welcome to try to create the emitters.

**Comment by aharui** [comment]
After thinking about this more, I think we want to add an option to the application/module compiler (MXMLJSC)  to generate an externs/typedefs file based on the actual results of the compile.  I don't think we need to put externs files in the SWCs.  The workflow should be more like how -link-report is used in Flex modules.

**Comment by kennylerma** [comment]
@aharui thanks for looking into this.  Ultimately, I'm hoping to keep workflow the same for using swc files as expected by any ActionScript developer.  I may not understand the total issue on the compiler side, but a SWC file already has the transpiled javascript in it.  If the swc is used as an external library, the compiler would still write out each needed js class file from the swc, but the real change would be with Google Closure.  When making a release build, Closure would be passed the external js classes as -externs and then compile the rest of the non-external classes.  Currently, I can pass the -externs argument to the Royale compiler, but I can't tell closure to exclude the classes in the extern also.  So, I have to do a separate custom build where I tell closure the specific files to compile and of course what to exclude.

As long as all the dependencies are provided, I would hope this would work, but that's my thought and I appreciate your help.

**Comment by kennylerma** [comment]
To be clear, this is the workflow that is working for me now, but I would like to see it handled by the compiler along with correcting the dependency issue.

**Comment by aharui** [comment]
IMO, it will make the SWCs really fat to additionally pack Externs in them.  And it will take longer to compile the SWC because we will have to transpile not only to JS but transpile again to Externs.  My thinking is that a whole bunch of SWCs may never be used as external libraries, so SWC developers would be faced with packing externs just-in-case.

Also, Google Closure Compiler doesn't run when building a SWC, it only runs when creating an application or module, and the Flex workflow for kicking classes out of the model is probably well-known to those migrating.  So teaching the Royale application compiler to generate the externs based on what classes from all SWCs were actually put in the output that will be loaded to provide those external dependencies.

Or maybe I'm not understanding what you are trying to do with your SWCs.

**Comment by kennylerma** [comment]
Yeah, I think you're misunderstanding and over-complicating the issue. Currently, creating a Royale SWC already has the generated javascript files included in the swc which can also be used as externs.  So, no need to create extern files. 

When using the swc as an external library in a project, those included javascript files in the swc can be used as externs for Closure.  We just need the royale compiler to tell closure how to use those files.  As in, which files should be compiled source and which should just be used as an extern for exclusion.  If the js files came from an external library swc when building a project, they should be used as a closure extern in the release build.

Here's my workflow now
1. Create a debug build to generate all the js files in the js-debug folder (this is part of making a release build already)
2. Build the files in js-debug with closure using --externs for files they are needed, but excluded in the finale output and --js for the source to be included in the final output.

`
java -jar compiler.jar --externs js-debug/class1.js --externs js-debug/class2.js --js js-debug/class3 --js js-debug/class4.js --compilation_level WHITESPACE_ONLY --dependency_mode=STRICT --entry_point=class4.js --js_output_file=module.js
`

The only additional thing I'm doing in my workflow is that I have my javascript files that are needed for --extern compiled by closure into a single javascript file.  So, I only have to list the one file like --extern myexternallibrary.js  This could be easily generated into the swc too.

Even if it was required to make SWC files bigger, it doesn't really matter.  Most as3 devs are not frequently re-building swc files as it's a shared library for other projects and doesn't add to the size of the release build simply by being a swc vs as3 files.

I hope I'm making a little more sense :)

**Comment by aharui** [comment]
I didn't think the .js files we pack in the SWCs could be used as externs.  They don't conform to the externs "spec".  You've tried this and it works?

**Comment by kennylerma** [comment]
They definitely work as externs.  I'm doing this is my production currently.  Also, I made a small test app for you.  The only issue that I forgot here is that you need load the Language.js and closure's base.js file in the html page first.  Normally, these are compiled into the whole build, but if you're splitting up the build, these need to be loaded separately.  What I do, is compile the Language, base and extern files into a single file using Closure to have a single file to load upfront first.

[ClosureTest.zip](https://github.com/apache/royale-compiler/files/2596039/ClosureTest.zip)

**Comment by aharui** [comment]
I have committed code that works as I proposed, and modified the original test case to show how to use it.  The additional step is to compile TestModule with -externs-report=<path to TestModule/bin/TestModule_externs.js

Then when compiling Main, add the option -js-compiler-option="--externs <path to TestModule_externs.js"

[COMPILER57.zip](https://github.com/apache/royale-compiler/files/2601257/COMPILER57.zip)

**Comment by kennylerma** [comment]
Thanks @aharui I think what you have is an excellent solution.  Being able to do all this all with the compiler is all I needed regardless of the how.  I'll check this out as soon as I can.  This is highly needed for larger applications like mine.

**Comment by kennylerma** [comment]
> I have committed code that works as I proposed, and modified the original test case to show how to use it. The additional step is to compile TestModule with -externs-report=<path to TestModule/bin/TestModule_externs.js
> 
> Then when compiling Main, add the option -js-compiler-option="--externs <path to TestModule_externs.js"
> 
> [COMPILER57.zip](https://github.com/apache/royale-compiler/files/2601257/COMPILER57.zip)

Hey @aharui did you ever add this into the builds.  I haven't seen this as an option in the nightly builds?  Maybe I'm just looking in the wrong place.

I'm not finding -externs-report

**Comment by aharui** [comment]
It is in the repo, so it should be in the nightly.  I don't have time to check myself right now.  Search the compiler source for "-externs-report".  Try running:

js/bin/mxmlc --help advanced

In my local build it showed up.

**Comment by kennylerma** [comment]
Ah, didn't realize it was under advanced.  Thanks
