### ISSUE TITLE
compiler omits any class-scoped conditional compilation blocks

### ISSUE THREAD

**Issue by mrchnk** [apache/royale-compiler#72]
Compiler omits any class-scoped conditional compilation blocks

```
class Main {

  CONFIG::DEBUG {
    private var _debug: int;
  }

}

```

No problem with conditional compilation "keywords" or function-scoped blocks

```
class Main {

  CONFIG::DEBUG
  private var _debug: int;

  function test(): void {
    CONFIG::DEBUG {
      trace(_debug);
    }
  }

}
```

I also created a minimal example project to reproduce that issue at https://github.com/mrchnk/royale-compiler-problems/tree/master/conditional-compilation-block

I found that bug in npm distribution of compiler @apache-royale/royale-js@0.9.4
That problem persists in the nightly build of compiler 1783

**Comment by Harbs** [comment]
Scoped declaration need the config statements attached directly (not sure the correct terminology.

So:
````
CONFIG__DEBUG
class Main{}
````
should work, but:
````
CONFIG__DEBUG
{
  class Main{}
}
````
will not.

Similarly it needs to be:
````
CONFIG::DEBUG
private var foo;
CONFIG::DEBUG
public function baz():void{}
````
rather than:

````
CONFIG::DEBUG
{
  private var foo;
  public function baz():void{}
}
````
AFAIK, blocks only work within a function.

**Comment by mrchnk** [comment]
That notation is working in flex and air sdk compilers. So It is expected to be working in Royale.
