### ISSUE TITLE
utf-8 error with degree symbol

### ISSUE THREAD

**Issue by kennylerma** [apache/royale-compiler#87]
I'm setting some text for a textfield, but when building, the compiler complains of a utf-8 error because of the º (degree symbol).  I can work around this using the below, but I believe the comiler should be able to handle this.

```as3
String.fromCharCode(0xB0);
```

**Comment by carlosrovira** [comment]
Hi Kenny, if you know where is the problem you think we have, could you create a patch and send us a PR so we can see it and merge if all is ok?
thanks

**Comment by kennylerma** [comment]
I'm not sure where to look since I'm not that familiar with the compiler or I would fix it.  If I find anything, I will certainly note it here.

**Comment by piotrzarzycki21** [comment]
Hey @kennylerma, 
Do you have `JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8` setup ?

**Comment by kennylerma** [comment]
Hey guys, I just realized it's actually and issue with the Closure compiler.  @piotrzarzycki21 I'll add that in and see if it makes difference.  Thanks.  Also, @piotrzarzycki21 I hadn't forgotten about getting you a as3 only build setup for Moonshine, just very busy as usual :)

**Comment by piotrzarzycki21** [comment]
> Hey guys, I just realized it's actually and issue with the Closure compiler. @piotrzarzycki21 I'll add that in and see if it makes difference. Thanks. Also, @piotrzarzycki21 I hadn't forgotten about getting you a as3 only build setup for Moonshine, just very busy as usual :)

I'm looking forward to your email! No hurry at all :) I know how busy some projects can be. :) Thank you!

**Comment by kennylerma** [comment]
Closing this, since it's related to using the Closure compiler separately
