### ISSUE TITLE
Bad "this"

### ISSUE THREAD

**Issue by Harbs** [apache/royale-compiler#90]
I have a class which has the following function:
````
    private function loadApi(endpoint:String):void{
      var request:URLRequest = RequestUtil.getRequest(endpoint);
      loader.onComplete = function (l:URLBinaryLoader):void
      {
        status = "complete";
        if(canceled){
          return;
        }
        var stringRes:String = l.data.readUTFBytes(l.data.length);
        if(stringRes){
          result = JSON.parse(stringRes);
        }
        complete(this);
      }
      loader.onError = function (l:URLBinaryLoader):void
      {
        status = "error";
        if(canceled){
          return;
        }
        var stringRes:String = l.data.readUTFBytes(l.data.length);
        result = JSON.parse(stringRes);
        error(this);
      }
      request.data = params;
      loader.load(request);
    }
````
It compiles to:
````
com.printui.services.APIService.prototype.com_printui_services_APIService_loadApi = function(endpoint) {
  var self = this;
  var /** @type {org.apache.royale.net.URLRequest} */ request = com.printui.utils.RequestUtil.getRequest(endpoint);
  this.loader.onComplete = function(l) {
    self.status = "complete";
    if (self.canceled) {
      return;
    }
    var /** @type {string} */ stringRes = l.data.readUTFBytes((l.data.length) >>> 0);
    if (stringRes) {
      self.result = JSON.parse(stringRes);
    }
    self.complete(this);
  };
  this.loader.onError = function(l) {
    self.status = "error";
    if (self.canceled) {
      return;
    }
    var /** @type {string} */ stringRes = l.data.readUTFBytes((l.data.length) >>> 0);
    self.result = JSON.parse(stringRes);
    self.error(this);
  };
  request.data = this.com_printui_services_APIService_params;
  this.loader.load(request);
};
````
`self.complete(this);` and `self.error(this);` are both pointing to the wrong `this`.

The code should be output as `self.complete(self);` and `self.error(self);`

**Comment by piotrzarzycki21** [comment]
Did you workaround somehow this?

**Comment by Harbs** [comment]
Manually adding `self` instead of `this` to the code...

**Comment by joshtynjala** [comment]
The compiler is actually working correctly, and this matches the behavior of SWF.

`self` is used in the generated output only when `this` is implicit. That's why `status = "complete";` turns into `self.status = "complete"`. However, if you had `this.status = "complete";` instead, the explicit `this` would not be replaced by `self` in the generated output.

Similarly, `complete(this)` turns into `self.complete(this)`. The first `this` in ActionScript is implicit, so it the JS gets `self`, and the second is explicit, so it remains as `this` in JS.

**Comment by carlosrovira** [comment]
Thanks for exposing this, I thought `this` was always the same hence we can remove it. Now I know  is not the case :). Thanks!

**Comment by Harbs** [comment]
Huh. I never would have guessed that would be "correct" behavior.

I wonder if this should be documented somewhere.

**Comment by carlosrovira** [comment]
I was talk in with @cottage14 to make a "Cookbook" section in the documentation. This will be another good one to catch there :)

**Comment by joshtynjala** [comment]
In the case of explicit `this`, the behavior is inherited from JS/ECMAScript. In JS, closures don't have the same `this` as the surrounding function. That's one of the reasons why they added "fat arrow" functions in JS. It allows JS developers to use `this` without saving a reference in a local variable.

JS also doesn't have a concept of implicit `this`. That was something added in AS3. The AS3 language designers probably should have made both explicit `this` and implicit `this` behave the same in closures because it leads to exactly this kind of confusion.

**Comment by aharui** [comment]
Maybe the compiler should warn about explicit 'this' in anonymous functions?

And how should the AS3 code:
```error(this)```

be written in AS3 to work in both SWF and JS?

**Comment by joshtynjala** [comment]
> Maybe the compiler should warn about explicit 'this' in anonymous functions?

That would be a nice addition!

> And how should the AS3 code be written in AS3 to work in both SWF and JS?

Basically the same way that we're doing it in JS for implicit `this`. Save `this` to a local variable outside of the closure, and then reference the local variable instead of `this` inside the closure.

**Comment by Harbs** [comment]
The warning sounds good.

Here's how I worked around the problem in my code:

````
    private function loadApi(endpoint:String):void{
      var self:APIService = this;
      var request:URLRequest = RequestUtil.getRequest(endpoint);
      loader.onComplete = function (l:URLBinaryLoader):void
      {
        status = "complete";
        if(canceled){
          return;
        }
        var stringRes:String = l.data.readUTFBytes(l.data.length);
        if(stringRes){
          result = JSON.parse(stringRes);
        }
        complete(self);
      }
      loader.onError = function (l:URLBinaryLoader):void
      {
        status = "error";
        if(canceled){
          return;
        }
        var stringRes:String = l.data.readUTFBytes(l.data.length);
        result = JSON.parse(stringRes);
        error(self);
      }
      request.data = params;
      loader.load(request);
    }
````

**Comment by Harbs** [comment]
Of course the work-around ends up with this ugly code...
````
  var self = this;
  var /** @type {com.printui.services.APIService} */ self = this;
````

**Comment by aharui** [comment]
I was wondering about that.  Doesn't Closure Compiler complain about that?  Fixing that seems worth doing.

**Comment by joshtynjala** [comment]
Yeah, the compiler should probably choose another name if `self` already exists in AS3.

**Comment by joshtynjala** [comment]
I successfully made a little prototype of the this/closure warning. I'll commit it once I polish things up.

**Comment by Harbs** [comment]
🆒
