### ISSUE TITLE
Vector.removeAt() returns Array in JS

### ISSUE THREAD

**Issue by yishayw** [apache/royale-compiler#91]
var item:SpreadTextData = spreadTextDataItems.removeAt(notificationBody.fromIndex) as SpreadTextData;

Transpiles to

    var /** @type {com.printui.model.SpreadTextData} */ item = spreadTextDataItems.splice(notificationBody.fromIndex, 1);

which is an Array

**Comment by greg-dove** [comment]
Duplicate of #92

**Comment by Harbs** [comment]
To be clear, the correct JS is:
`var /** @type {A} */ item = vectorAsArray.splice(index, 1)[0];`

instead of:
`var /** @type {A} */ item = vectorAsArray.splice(index, 1);`

**Comment by Harbs** [comment]
Fixed in 34ff8d4
