### ISSUE TITLE
Change to XML.children() is non-conforming/breaks tests

### ISSUE THREAD

**Issue by greg-dove** [apache/royale-compiler#93]
@Harbs the change in https://github.com/apache/royale-asjs/commit/64eb73564aa9f3186477416cee575ceed1625cf9 causes wrong results. 
XML.children() is not just elements, that includes text and comments etc... The change breaks some of the tests in the manualtests project which tests XML across swf and javascript. (I will port these tests to RoyaleUnit at some point in the near future, so it will be more obvious if there is a breaking change in the future)

You can also check this quickly by pasting the following in Adobe Animate:

```
XML.ignoreWhitespace = true;
XML.ignoreComments = false;
var xml:XML = new XML('<root><!-- my test comment --></root>');

trace("-->>"+xml.children().toXMLString()+"<<--") // -->><!-- my test comment --><<--
trace(xml.children().length()) //1
```

**Comment by Harbs** [comment]
I made this change to fix a different breaking change that you did.

The issue was that text nodes were being returned, and they shouldn't.

The fact that (empty) text nodes are now included in the internal children property has caused a number of issues that I've noticed. I'm not sure how to best deal with that.

**Comment by greg-dove** [comment]
It's pretty hard to manage any of this unless we use the unit tests. We need something that is methodically managed, because it's too complex to verify 'breaking' behavior via adhoc testing, and we'll keep taking one step back as we take another step forward elsewhere. 
I can't consider anything I did as 'breaking' when there is not yet test coverage for that. We need to keep adding tests. If you see something I do that 'breaks' something that is not covered, please feel free to call me out on it... or better still add a failing test, and I will address it. I realise it will be easier once these tests are ported to RoyaleUnit because then it will break the build if something is not right, so I will try to get there next week.  Meanwhile if you can give me a simple example of something that was not working right with XML.children(), I will take a look tomorrow.

**Comment by Harbs** [comment]
Agreed.

**Comment by Harbs** [comment]
It seems I was wrong. When XML.ignoreWhitespace is false, whitespace text nodes are supposed to be returned by children().

I'm trying to figure out why I thought this change was necessary.

**Comment by greg-dove** [comment]
@Harbs I have ported the XML tests across to RoyaleUnit.
The failing tests are marked with [Ignore] to avoid breaking the build.
here: https://github.com/apache/royale-asjs/blob/be1f5a74cabc1fec32bc9d7c1fd6a3d7dcc382e9/frameworks/projects/XML/src/test/royale/flexUnitTests/xml/XMLTesterGeneralTest.as#L162
here:https://github.com/apache/royale-asjs/blob/be1f5a74cabc1fec32bc9d7c1fd6a3d7dcc382e9/frameworks/projects/XML/src/test/royale/flexUnitTests/xml/XMLTesterGeneralTest.as#L577
here: https://github.com/apache/royale-asjs/blob/be1f5a74cabc1fec32bc9d7c1fd6a3d7dcc382e9/frameworks/projects/XML/src/test/royale/flexUnitTests/xml/XMLTesterGeneralTest.as#L700
and here: https://github.com/apache/royale-asjs/blob/be1f5a74cabc1fec32bc9d7c1fd6a3d7dcc382e9/frameworks/projects/XML/src/test/royale/flexUnitTests/xml/XMLTesterGeneralTest.as#L726

I think these are all likely related to the XML.children() errors. I plan to restore these tests to passing on on my Monday. I will also add more tests to cover variations in ignoreWhiteSpace, ignoreProcessingInstructions, ignoreComments etc as they relate to return values for children() method. Hopefully by doing so, I can address the original issue you were seeing, which I'm guessing might have been related to something like that.

**Comment by greg-dove** [comment]
@Harbs I could not see issues with the variations of the parsing flags on children(). I added a new test for that. I am closing this issue because it is addressed. Can you please open a new issue if you see the original  problem you had, and I will try to figure it out. In a couple of days I am likely to be restricted for time for the following 6-7 days, but I may have time tomorrow to address it, if you can log an issue during your day.

**Comment by Harbs** [comment]
I was having trouble finding what my issue was.

I'm going to have to do a lot of testing before I use these changes (although they look right). I'll likely be a couple/few weeks before I will have the time to do that.
