### ISSUE TITLE
TabBar example fails

### ISSUE THREAD

**Issue by yishayw** [apache/royale-compiler#97]
Steps to reproduce:

- fetch branch SparkTextButtonItemRenderer  from royale-asjs
- build MXRoyale and SparkRoyale
- build MXRoyale HelloWorld example

Result:
C:\dev\flexjs\royale-asjs\examples\mxroyale\HelloWorld\SparkRoyale.swc:defaults.css(181): col: 2 Error: 'SparkTextButtonItemRenderer' is not defined.

**Comment by aharui** [comment]
Just from looking at the branch commit:

'SparkTextButtonItemRenderer' has been added as a Type Selector.  Type Selectors are defined in a namespace declared at the top of the defaults.css file.  In this case:

`@namespace "library://ns.apache.org/royale/spark";`

The file `src/main/resources/spark-royale-manifest.xml` did not appear to be changed in the commit to add 'SparkTextButtonItemRenderer' to the namespace.  It might have worked if the namespace defined a folder path, but by convention, the framework swcs use namespace URIs.

**Comment by yishayw** [comment]
Didn't know that, I thought adding to SparkClasses.as was enough. Thanks.

**Comment by Harbs** [comment]
Actually, it's only necessary to add classes to the [swc]Classes file if it's **_not_** defined in the manifest. Classes defined in the manifest are always included in the SWC. The `*Classes` files are a hack to get the rest of the classes which are not in the dependency list included in the SWC.

HTH...
